sed -i 's/className={`flex items-center gap-3 w-full p-2.5 rounded-xl transition-colors text-left ${currentTab === '\''emergency'\'' ? '\''bg-red-50 text-red-700'\'' : '\''hover:bg-slate-50 text-slate-700'\''}`}/className={`flex items-center gap-3 w-full p-4 sm:p-2.5 rounded-2xl sm:rounded-xl transition-colors text-left sm:bg-transparent ${currentTab === '\''emergency'\'' ? '\''bg-red-50 sm:bg-red-50 border-red-100 text-red-700'\'' : '\''bg-white border-slate-100 sm:border-transparent hover:bg-slate-50 text-slate-700'\''} border sm:border-transparent shadow-sm sm:shadow-none`}/g' src/App.tsx

sed -i 's/className={`flex items-center gap-3 w-full p-2.5 rounded-xl transition-colors text-left ${currentTab === '\''my_activity'\'' ? '\''bg-emerald-50 text-emerald-700'\'' : '\''hover:bg-slate-50 text-slate-700'\''}`}/className={`flex items-center gap-3 w-full p-4 sm:p-2.5 rounded-2xl sm:rounded-xl transition-colors text-left sm:bg-transparent ${currentTab === '\''my_activity'\'' ? '\''bg-emerald-50 sm:bg-emerald-50 border-emerald-100 text-emerald-700'\'' : '\''bg-white border-slate-100 sm:border-transparent hover:bg-slate-50 text-slate-700'\''} border sm:border-transparent shadow-sm sm:shadow-none`}/g' src/App.tsx

sed -i 's/className="flex items-center gap-3 w-full p-2.5 rounded-xl transition-colors text-left hover:bg-blue-50 text-slate-700"/className="flex items-center gap-3 w-full p-4 sm:p-2.5 rounded-2xl sm:rounded-xl transition-colors text-left bg-white sm:bg-transparent border border-slate-100 sm:border-transparent hover:bg-blue-50 text-slate-700 shadow-sm sm:shadow-none"/g' src/App.tsx

sed -i 's/className="flex items-center gap-3 w-full p-2.5 rounded-xl transition-colors text-left hover:bg-teal-50 text-slate-700"/className="flex items-center gap-3 w-full p-4 sm:p-2.5 rounded-2xl sm:rounded-xl transition-colors text-left bg-white sm:bg-transparent border border-slate-100 sm:border-transparent hover:bg-teal-50 text-slate-700 shadow-sm sm:shadow-none"/g' src/App.tsx

sed -i 's/className="flex items-center gap-3 w-full p-2.5 rounded-xl transition-colors text-left hover:bg-cyan-50 text-slate-700"/className="flex items-center gap-3 w-full p-4 sm:p-2.5 rounded-2xl sm:rounded-xl transition-colors text-left bg-white sm:bg-transparent border border-slate-100 sm:border-transparent hover:bg-cyan-50 text-slate-700 shadow-sm sm:shadow-none"/g' src/App.tsx

