#!/bin/bash
awk '
/if \(process.env.NODE_ENV !== "production"\) \{/ {
  print "  app.get(\"/api/storage/files\", verifyToken, async (req, res) => {"
  print "    try {"
  print "      const accountId = process.env.CLOUDFLARE_R2_ACCOUNT_ID;"
  print "      const accessKeyId = process.env.CLOUDFLARE_R2_ACCESS_KEY_ID;"
  print "      const secretAccessKey = process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY;"
  print "      const bucketName = process.env.CLOUDFLARE_R2_BUCKET_NAME;"
  print "      let publicUrl = process.env.CLOUDFLARE_R2_PUBLIC_URL || \"\";"
  print "      if (!accountId || !accessKeyId || !secretAccessKey || !bucketName) {"
  print "        return res.status(400).json({ error: \"Cloudflare R2 not fully configured\" });"
  print "      }"
  print "      const r2Client = new S3Client({"
  print "        region: \"auto\","
  print "        endpoint: `https://${accountId}.r2.cloudflarestorage.com`,"
  print "        credentials: {"
  print "          accessKeyId,"
  print "          secretAccessKey,"
  print "        },"
  print "      });"
  print "      const prefix = (req.query.prefix as string) || \"\";"
  print "      const command = new ListObjectsV2Command({"
  print "        Bucket: bucketName,"
  print "        Prefix: prefix,"
  print "      });"
  print "      const data = await r2Client.send(command);"
  print "      if (publicUrl.endsWith(\"/\")) {"
  print "        publicUrl = publicUrl.slice(0, -1);"
  print "      }"
  print "      const files = (data.Contents || []).map(file => ({"
  print "        key: file.Key,"
  print "        size: file.Size,"
  print "        lastModified: file.LastModified,"
  print "        url: `${publicUrl}/${file.Key}`"
  print "      }));"
  print "      files.sort((a, b) => {"
  print "        if (!a.lastModified) return 1;"
  print "        if (!b.lastModified) return -1;"
  print "        return new Date(b.lastModified).getTime() - new Date(a.lastModified).getTime();"
  print "      });"
  print "      res.json({ files });"
  print "    } catch (error: any) {"
  print "      console.error(\"Error listing files:\", error);"
  print "      res.status(500).json({ error: error.message });"
  print "    }"
  print "  });\n"
  print "  app.delete(\"/api/storage/files\", verifyToken, async (req, res) => {"
  print "    try {"
  print "      const { key } = req.body;"
  print "      if (!key) {"
  print "        return res.status(400).json({ error: \"File key is required\" });"
  print "      }"
  print "      const accountId = process.env.CLOUDFLARE_R2_ACCOUNT_ID;"
  print "      const accessKeyId = process.env.CLOUDFLARE_R2_ACCESS_KEY_ID;"
  print "      const secretAccessKey = process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY;"
  print "      const bucketName = process.env.CLOUDFLARE_R2_BUCKET_NAME;"
  print "      if (!accountId || !accessKeyId || !secretAccessKey || !bucketName) {"
  print "        return res.status(400).json({ error: \"Cloudflare R2 not fully configured\" });"
  print "      }"
  print "      const r2Client = new S3Client({"
  print "        region: \"auto\","
  print "        endpoint: `https://${accountId}.r2.cloudflarestorage.com`,"
  print "        credentials: {"
  print "          accessKeyId,"
  print "          secretAccessKey,"
  print "        },"
  print "      });"
  print "      const command = new DeleteObjectCommand({"
  print "        Bucket: bucketName,"
  print "        Key: key,"
  print "      });"
  print "      await r2Client.send(command);"
  print "      res.json({ success: true });"
  print "    } catch (error: any) {"
  print "      console.error(\"Error deleting file:\", error);"
  print "      res.status(500).json({ error: error.message });"
  print "    }"
  print "  });\n"
}
{ print }
' server.ts > temp.ts && mv temp.ts server.ts
